-- OrderStatus: add PROCESSING, REFUNDED, COMPLETED. Stock deduct only at PROCESSING.
ALTER TABLE `orders` MODIFY COLUMN `status` ENUM('PENDING', 'CONFIRMED', 'PAID', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'RETURNED', 'REFUNDED', 'COMPLETED', 'CANCELED') NOT NULL DEFAULT 'PENDING';
