-- OrderStatus: add CONFIRMED, RETURNED; rename CANCELLED -> CANCELED
-- Step 1: Add new enum values (keep CANCELLED for existing data)
ALTER TABLE `orders` MODIFY COLUMN `status` ENUM('PENDING', 'PAID', 'CANCELLED', 'SHIPPED', 'DELIVERED', 'CONFIRMED', 'CANCELED', 'RETURNED') NOT NULL DEFAULT 'PENDING';

-- Step 2: Migrate CANCELLED to CANCELED
UPDATE `orders` SET `status` = 'CANCELED' WHERE `status` = 'CANCELLED';

-- Step 3: Remove CANCELLED from enum
ALTER TABLE `orders` MODIFY COLUMN `status` ENUM('PENDING', 'PAID', 'CONFIRMED', 'SHIPPED', 'DELIVERED', 'CANCELED', 'RETURNED') NOT NULL DEFAULT 'PENDING';
